networks:
  prometheus:
    name: prometheus
    driver: bridge
services:
  python-application:
    build:
      context: python-application
    container_name: python-application
    image: python-application
    ports:
      - "81:5000"
    networks:
      - prometheus
  prometheus:
    container_name: prometheus-svc
    build:
      context: .
      dockerfile: prometheus.Dockerfile
    ports: 
      - "9091:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    networks:
      - prometheus
  grafana:
    image: grafana/grafana:11.6.1
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - prometheus
  grafana-dashboards:
    build:
      context: .
      dockerfile: grafana-dashboards.Dockerfile
    depends_on:
      - grafana
    command: >
      /bin/sh -c "
        echo 'waiting for grafana'
        sleep 10s
        curl --request POST http://grafana:3000/api/datasources --header 'Content-Type: application/json' -d @datasources.json
        curl --request POST http://grafana:3000/api/dashboards/db --header 'Content-Type: application/json' -d @dashboard.json"
    networks:
      - prometheus