apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: ${{values.description}}
  annotations:
    github.com/project-slug: ${{values.githubOrg}}/${{values.githubRepoName}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - spring-boot
    - java
    - manual-deployment
    - aws-ec2
spec:
  type: service
  lifecycle: experimental
  owner: guests
