apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Creates a Java Spring boot app with prometheus and loki integration
  name: java-monitoring-lab
  title: Java Spring boot app with prometheus and loki integration
spec:
  owner: guests
  type: service
  parameters:
    - title: Configuration Options
      required:
        - name
      properties:
        name:
          type: string
          description: name of this application! (eg. [YOUR-NAME]-app)
        domain:
          type: string
          description: Base domain for the platform
          default: eci-idp.click
          ui:widget: hidden
    
    - title: Select Parent Stack
      properties:
        parentSystem:
          title: Parent System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: system
              spec.stackType: observability-stack
            allowArbitraryValues: false
    - title: Choose a location
      description: |
        This section will ask for details about the Owner and Repository name which will then be used 
        to create a repository in that location using your GitHub credentials.
      required:
        - repoUrl
        - collaborators
      properties:
        repoUrl:
          title: Enter an Owner and Repository Name
          description: |
            The Owner should be your GitHub org.
          type: string
          default: github.com?owner=educational-idp-MR
          ui:field: RepoUrlPicker
          ui:options:
            allowedOrganizations:
              - educational-idp-MR
            allowedHosts:
              - github.com
        collaborators:
          title: GitHub Collaborators
          description: |
            GitHub usernames to add as collaborators to the repository.
            You can add multiple users by clicking "Add Item".
          type: array
          items:
            type: string
          ui:options:
            orderable: false
        
  steps:
    - id: extract-parent-name
      name: Extract Parent System Name
      action: roadiehq:utils:jsonata
      input:
        data:
          parentSystem: ${{parameters.parentSystem}}
        expression: '$substringAfter(parentSystem, "/")'

    - id: debug-input-collaborators
      name: Debug - Input Collaborators
      action: debug:log
      input:
        message: "Input collaborators from parameters"
        listWorkspace: false
        extra:
          collaborators: ${{ parameters.collaborators }}
          collaboratorsType: ${{ typeof(parameters.collaborators) }}

    - id: process-collaborators
      name: Process Collaborators
      action: roadiehq:utils:jsonata
      input:
        data:
          collaborators: ${{ parameters.collaborators }}
        expression: |
          (
            $collaboratorsList := $type(collaborators) = "array" ? collaborators : [collaborators];
            $map($collaboratorsList, function($user) {
              {
                "user": $user,
                "access": "push"
              }
            })
          )

    - id: debug-output-collaborators
      name: Debug - Processed Collaborators
      action: debug:log
      input:
        message: "Processed collaborators output"
        listWorkspace: false
        extra:
          processedCollaborators: ${{ steps.process-collaborators.output.result }}
          resultType: ${{ typeof(steps.process-collaborators.output.result) }}
          rawResult: ${{ steps['process-collaborators'].output }}

    - id: template
      name: Generating component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{parameters.name}}
          parentSystem: ${{parameters.parentSystem}}
          cleanParentSystem: ${{ steps['extract-parent-name'].output.result }}
          githubOrg: ${{parameters.repoUrl | parseRepoUrl.owner}}
          githubRepoName: ${{parameters.repoUrl | parseRepoUrl.repo}}
          domain: ${{parameters.domain}}

    - id: publish
      name: Publicando en GitHub
      action: publish:github
      input:
        description: ${{parameters.description}}
        repoUrl: ${{parameters.repoUrl}}
        defaultBranch: main
        gitCommitMessage: "Initial Url Shortener app  with basic metrics"
        repoVisibility: public
        protectDefaultBranch: false
        collaborators: ${{ steps['process-collaborators'].output.result }}
    
    #Add little delay to allow the repository to be created
    - id: sleep
      name: Some magic is happening... enjoy a tinto meanwhile 🇨🇴
      action: roadiehq:utils:sleep
      input:
        amount: 5

    - id: dispatch-workflow
      name: Dispatch ECR Push Workflow
      action: github:actions:dispatch
      input:
        repoUrl: ${{parameters.repoUrl}}
        workflowId: ecr-push.yml
        branchOrTagName: main
        workflowInputs:
          version: "0.0.0"

    - id: create-argocd-app
      name: Create ArgoCD App
      action: cnoe:create-argocd-app
      input:
        appName: ${{parameters.name}}
        appNamespace: ${{parameters.name}}-monitoring
        argoInstance: in-cluster
        projectName: default
        repoUrl: ${{ steps['publish'].output.remoteUrl }}
        path: "kustomize/base"
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repositorio GitHub
        url: ${{ steps['publish'].output.remoteUrl }}
      
