---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: This is a Java Spring boot app with prometheus and loki integration
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'entity-id=${{values.name}}'
    backstage.io/kubernetes-namespace: ${{values.appNamespace}}
    argocd/app-name: ${{values.name | dump}}
  links:
    - url: https://${{values.name}}.${{values.cleanParentSystem}}.${{values.domain}}/api/
      title: Url Shortener App 
      icon: externalLink
spec:
  owner: guests
  lifecycle: experimental
  type: service
  system: ${{values.parentSystem | dump}}
