---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: student
spec:
  memberOf: [students]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: students
spec:
  type: team
  children: []
