apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: lab de java
  name: lab-2
  title: lab de java
  tags:
    - test
    - laboratory
    - intermediate

spec:
  owner: professors
  type: service
  
  parameters:
    # ========================================
    # Configuración del Laboratorio
    # ========================================
    - title: Configuración del Proyecto
      required:
        - name
      properties:
        name:
          type: string
          title: Nombre del Proyecto
          description: |
            Nombre para tu instancia de este laboratorio (ej. mi-proyecto-lab)
            Usa minúsculas, números y guiones.
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
          ui:placeholder: mi-proyecto
        
        description:
          type: string
          title: Descripción (Opcional)
          description: Personaliza la descripción de tu proyecto
          default: lab de java
          ui:widget: textarea
        
        domain:
          type: string
          description: Dominio base de la plataforma
          default: eci-idp.click
          ui:widget: hidden
    
    # ========================================
    # Sistema Padre (si aplica)
    # ========================================
    
    # ========================================
    # Repositorio GitHub
    # ========================================
    - title: Repositorio GitHub
      description: El laboratorio se creará como un repositorio en GitHub
      required:
        - repoUrl
        - collaborators
      properties:
        repoUrl:
          title: Ubicación del Repositorio
          description: Selecciona la organización y nombre del repositorio
          type: string
          default: github.com?owner=educational-idp-MR
          ui:field: RepoUrlPicker
          ui:options:
            allowedOrganizations:
              - educational-idp-MR
            allowedHosts:
              - github.com
        
        collaborators:
          title: Colaboradores de GitHub
          description: |
            Usuarios de GitHub que tendrán acceso al repositorio.
            Agrega varios usuarios haciendo clic en "Add Item".
          type: array
          items:
            type: string
            ui:placeholder: github-username
          ui:options:
            orderable: false

  # ========================================
  # PASOS DE EJECUCIÓN
  # ========================================
  steps:
    # Paso 1: Extraer nombre del sistema padre (si existe)
    
    # Paso 2: Procesar colaboradores
    - id: process-collaborators
      name: Procesar Lista de Colaboradores
      action: roadiehq:utils:jsonata
      input:
        data:
          collaborators: ${{ parameters.collaborators }}
        expression: |
          (
            $collaboratorsList := $type(collaborators) = "array" ? collaborators : [collaborators];
            $result := $map($collaboratorsList, function($user) {
              {
                "user": $user,
                "access": "push"
              }
            });
            $type($result) = "array" ? $result : [$result]
          )
    
    # Paso 3: Generar el contenido desde el skeleton
    - id: template
      name: Generando Estructura del Proyecto
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{parameters.name}}
          description: ${{parameters.description}}
          githubOrg: ${{parameters.repoUrl | parseRepoUrl.owner}}
          githubRepoName: ${{parameters.repoUrl | parseRepoUrl.repo}}
          domain: ${{parameters.domain}}
          # Metadata del laboratorio original
          labName: lab-2
          labDifficulty: intermediate
          labDuration: 2h
    
    # Paso 4: Publicar en GitHub
    - id: publish
      name: Publicando Repositorio en GitHub
      action: publish:github
      input:
        description: ${{parameters.description}}
        repoUrl: ${{parameters.repoUrl}}
        defaultBranch: main
        gitCommitMessage: "Initial commit: ${{parameters.name}}"
        repoVisibility: public
        protectDefaultBranch: false
        collaborators: 
    
    # Paso 5: Esperar a que el repositorio esté listo
    - id: sleep
      name: Preparando repositorio...
      action: roadiehq:utils:sleep
      input:
        amount: 3
    
    # Paso 6: Registrar en el catálogo de Backstage
    - id: register
      name: Registrar en Backstage Catalog
      action: catalog:register
      input:
        repoContentsUrl: 
        catalogInfoPath: '/catalog-info.yaml'

  # ========================================
  # ENLACES DE SALIDA
  # ========================================
  output:
    links:
      - title: Ver en Backstage
        url: https://backstage.${{parameters.domain}}/catalog/default/component/${{parameters.name}}
      
      - title: Repositorio en GitHub
        url: 
      
      - title: Documentación
        url: /blob/main/README.md
