apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: educational-idp-templates
  description: A collection of example templates
spec:
  targets:
    - ./kubernetes-prometheus-grafana/template.yaml
    - ./flask-app-with-prometheus/template.yaml
    - ./java-monitoring-lab/template.yaml
    - ./contribute-new-lab/template.yaml
# ---
# apiVersion: backstage.io/v1alpha1
# kind: Location
# metadata:
#   name: basic-organization
#   description: Basic organization data
# spec:
#   targets:
#     - ./organization/guests.yaml
