apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.name}}-monitoring
  labels:
    app: ${{values.name}}-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.name}}-monitoring
  template:
    metadata:
      labels:
        app: ${{values.name}}-monitoring
    spec:
      containers:
      - name: ${{values.name}}-monitoring
        image: ChangeMe #TODO: Change this to your image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ${{values.name}}-monitoring
  labels:
    app: ${{values.name}}-monitoring
spec:
  selector:
    app: ${{values.name}}-monitoring
  ports:
  - port: 80
    targetPort: 5000
    name: http
  type: ClusterIP