---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "lab-2"
  description: "lab de java"
  annotations:
    # Documentación técnica en Backstage
    backstage.io/techdocs-ref: dir:.
    
    # Si tu laboratorio despliega en Kubernetes, descomenta:
    # backstage.io/kubernetes-label-selector: 'entity-id=lab-2'
    # backstage.io/kubernetes-namespace: lab-2
    
    # Si usa ArgoCD, descomenta:
    # argocd/app-name: "lab-2"
  
  links:
    - url: https://github.com/educational-idp-MR/
      title: Repositorio GitHub
      icon: github
    
    # Si tu laboratorio despliega una aplicación, descomenta y personaliza:
    # - url: https://lab-2.eci-idp.click
    #   title: Aplicación Desplegada
    #   icon: dashboard

  tags:
    - laboratory
    - student-project
    - 

spec:
  type: service
  lifecycle: experimental
  owner: students
  
  # Sistema padre (si el laboratorio lo define)
